### ISSUE TITLE
attachScale function removes "Display name"-attribute from scale data

### ISSUE THREAD

**Issue by phjordan** [ScientificDataFormat/SDF-Modelica#3]
Using SDF library v0.4.4 Build 1 in Dymola 2025x

When creating a .sdf file using the functions provided with the SDF library (SDF.Functions), the _attachScale_-function seems to remove the "Display name" attribute from the Scale vector.

This happens for 1D double vector data, I have not tested other functions.

To reproduce, open the attached modelica package 
[SdfCreationFunctions.zip](https://github.com/user-attachments/files/17633261/SdfCreationFunctions.zip)
in Dymola. Functions _File1_ and _File2_ create .sdf files with one and two 1D double vectors, respectively. The data sets in the generated .sdf files contain a "Display name" attribute as expected.
Function _File3_  is identical to _File2_, except the Modelica function _SDF.Functions.attachScale_ is used to make the first of the two vectors the scale of the second. In the resulting .sdf file, the "Display Name" attribute  of the vector set as scale is empty.

I have only looked at the resulting .sdf files using the SDF-Editor v1.3.4

**Comment by t-sommer** [comment]
The function `SDF.Functions.attachScale()` has a parameter `dimensionName=""` that sets the display name of the scale. With its default value (empty string) it will remove any previous display name from the scale.
